Makefile

Pre-stage support for 'help' target to Makefile, so that associated
changes to CI-build scripts can be pre-staged (to address issue #371).
All this is needed to smooth the integration of larger Makefile
rework coming up under PR #332 .

(#370) Add 'help' to Makefile, report minimal usage msg.

---

ci/steps.lib.yml

Upcoming PR #332 changes Makefile targets to build the library. Those
changes will require changes to the commands invoked by CI-jobs to build
and test the library. This commit pre-stages those CI-build script
changes, so that the upcoming Makefile changes can be tested independently
before they are merged to /main. (This change depends on PR #372, which
adds minimal support for 'help' target to Makefile.)

(#371) Pre-stage CI-jobs' script changes to work with Makefile changes.

---

test.sh

Re-indent long-lines to invove tests via run_with_timing() to
properly align multiple parameters. Improve readability and
consistency in test.sh .
---
While re-formatting lines to align parameters, also re-indented set of single-line calls to `run_with_timing()` to indent the calls as multi-line statement. This way, all calls to this function are consistent in the entire file.

(#378) Minor re-indentation of run_with_timing() calls

---

Makefile
ci/steps.lib.yml

This commit cleans-up CI-scripts of 'make debug' which is no
longer needed. CI jobs drive 'make' using BUILD_ env-vars to
control release v/s debug builds. Makefile no longer needs to
support 'debug' target. Update the 'help' message to list
supported targets.
----
Updated `make help` looks like follows:
```
Fusion-LocalVM:[43] $ make help
Usage: make [<target>]
Supported targets: clean all libs all-tests run-tests test-results install
Environment variables controlling the build:
[... rest of the output is unchanged ...]
```
NOTE: This change has to go in conjunction with `ci/apply-pipeline.sh` to update the CI-scripts in the CI machinery.
For now, I have applied this manually, just to make sure that this PR's CI-jobs succeed. Once they pass, I will revert the CI-scripts to those in …

(#377) Purge 'debug' as make target. Fix CI-build scripts.

---

src/platform_linux/platform.c
src/platform_linux/platform.h
src/platform_linux/platform_inline.h
src/platform_linux/platform_types.h
src/task.c
src/trunk.c

Adds an `owner` field to `platform_mutex`, which is used for asserting that threads are correctly locking and unlocking the mutex.
Fixes a bug where `trunk_bundle_live` and `trunk_bundle_live_for_pivot` would answer incorrectly. This is because they used the bundle start branch to determine liveness, but accessing the start branch of a dead bundle results in undefined behavior.
Partially fixes the convoluted logic in `trunk_flush_fullest`, where the return value would frequently be FALSE, despite a successful flush.

Add ownership to `platform_mutex`, fix/cleanup bundle accounting

---

tests/functional/splinter_test.c

Extract out shared / repeated code between `--perf` and `--parallel-perf` test cases of splinter_test to sub-functions. Introduce the following:
- compute_per_table_inserts()
- load_thread_params()
- do_n_thread_creates()
- do_n_async_ctxt_inits(), do_n_async_ctxt_deinits()
- splinter_perf_inserts() - which wraps up few of above functions to
drive the inserts-phase of the workload
- splinter_perf_lookups() - drives lookups phase of the workload
- splinter_perf_range_lookups() - drives range lookups phase
Rework chunks of test_splinter_perf() and test_splinter_parallel_perf()
to invoke these helper / refactored functions.
This commit lays down the groundwork for future refactoring of other test cases in this test, to improve code-sharing.
-----
**NOTE**: This `splinter_test --perf` is …

(#334) Refactor / modularize shared code in splinter_test perf tests

---

Makefile
src/default_data_config.c
src/platform_linux/laio.c
src/platform_linux/laio.h
src/splinterdb.c
src/trunk.c
test.sh
tests/config.c
tests/config.h
tests/functional/splinter_test.c
tests/unit/limitations_test.c
tests/unit/splinter_test.c

This commit adds checks in different places to validate that the documented page-, extent-, key-size limits are properly enforced.
Some asserts trapping these limits are converted to error messages. Add new test, limitations_test, to verify that different Splinter config / init / create interfaces fail (as expected) when used with illegal values.
----
**NOTE**: This is really _not new code-dev_, but **mainly tightening error checks** in some of the test-config interfaces, and in a few places in Splinter main code. This implements checks to verify that our supported page- / extent-size and max-key-size limits are properly enforced, with error messages, in most commonly seen interfaces. New test dev is done to verify these checks. Fixes issue #341 .
----
Here is a successful run of the …

(#341) Add tests to verify that various hard-limits are enforced.

---

test.sh

Nightly tests executed under nightly_test_limitations() were broken
as the test binaries were being executed from bin/ dir. This has been
reworked to live under build/bin. Regression crept in from #341
@SHA f5de8cf. Fix is to consistently use $BINDIR handle to locate test
binaries.

Fix invocation of test binaries with $BINDIR path prefix.

---

tests/unit/splinterdb_quick_test.c

Couple of test cases in splinterdb_quick_test.c were missing a call
to splinterdb_lookup_result_deinit() before exiting the test case.
This causes memory leaks, detected on ASAN-test-runs. This commit
fixes those problems.

(#391) Fix memory leaks found in ASAN-test runs of quick unit-tests.

---

src/memtable.c
src/memtable.h
src/splinterdb.c
src/trunk.c

Addresses #389.
Another way to address 389 would be to double the default memtable size.  I think that is probably the better way, since it gives users more accurate control over how much cache the memtable can consume.

set extents_per_memtable to 2 * memtable_capacity

---

include/splinterdb/splinterdb.h
src/rc_allocator.c
src/rc_allocator.h
src/splinterdb.c
src/task.c
src/task.h
src/trunk.c
src/trunk.h
tests/functional/btree_test.c
tests/functional/cache_test.c
tests/functional/filter_test.c
tests/functional/log_test.c
tests/functional/splinter_test.c
tests/functional/test.h
tests/functional/ycsb_test.c
tests/unit/limitations_test.c
tests/unit/splinter_test.c
tests/unit/splinterdb_quick_test.c
tests/unit/splinterdb_stress_test.c

Minor rework to tighten the interfaces which close / deinit sub-system handles:
- Rename "dismount" to "unmount"; as in 'trunk_unmount()'
- splinterdb_close(), trunk_unmount(), test_deinit_task_system(),
task_system_destroy() now receive an addr-of-ptr to handle, and NULL-out
the handle upon a successful close / unmount / deinit. This will cause
a seg-fault if caller tries to access said handle after it has been closed.
-----
While developing C-example programs, I ran into some bad code (my own) while calling `splinterdb_close()`. 
I corrected the interface in my private branch, and then recollected that I had proposed to do this cleanup some weeks ago.
Peeling off this cleanup item as its own PR so that this rework can be done independently. 
It will help write out the C-example programs …

(#396) NULL-out input handle(s) after close(). Rename dismount -> unmount(), where applicable.

---

test.sh
tests/functional/splinter_test.c

Earlier refactoring of splinter_test.c [under SHA 3b7bc58] caused a
bug which is probably the cause for excessively long run-times for
this test case. (The # of range lookups done were inordinately high.)
This commit fixes that bug, and additionally:
- Adds extra progress messages under --verbose-progess flag.
- Fixes minor (divide-by-zero) bugs when this test is run with very
small # of --num-inserts rows.
- Enables splinter_test --perf in nightly runs with --verbose-progress
flag to run w/large data set
- Includes a quick perf run call to exercise new --verbose-progress
and --num-inserts options.
----
NOTE : This started a change set to add --verbose` progress instrumentation to perf tests. And while triaging the slow perf-test runs, discovered (Thanks to Alex!) a bug that had crept in …

(#354) splinter_test --perf: Fix bug in range-lookups test code.

---

src/allocator.h
src/clockcache.c
src/rc_allocator.c
src/rc_allocator.h
tests/unit/splinter_test.c

Test splinter_test --perf, and some other tests, are randomly tripping up a
debug assertion in clockcache_get_internal(), which reports that we
are trying to cache a page from an unallocated extent. This problem is
not reproducible. This commit improves the assertion message to report
addresses involved, and also calls-out to a print method to dump out
allocated extents bitmap. (This should only occur very rarely, if at all.)
----
This arises from the triaging of the assertion failure reported in issue #305. Several attempts have been made to try to repro it, but no avail.
Rather than closing out the issue as "not reproducible", I am adding some instrumentation, that will only trip in debug builds, to report more data when the assertion trips. This may give us some more clues for further …

(#305) Add instrumentation to track assertion in clockcache_get_internal()

---

Makefile

Signed-off-by: Eric Lagergren <eric@ericlagergren.com>

use xargs -I{} instead of the deprecated xargs -i

---

src/platform_linux/platform_types.h

It's non-standard and not actually used.
Signed-off-by: Eric Lagergren <eric@ericlagergren.com>

remove dependency on malloc.h

---

include/splinterdb/data.h
src/allocator.h
src/btree.c
src/btree.h
src/btree_private.h
src/clockcache.c
src/data_internal.h
src/memtable.h
src/routing_filter.h
src/task.c
src/task.h
src/trunk.c
src/trunk.h

This commit is for code clean-up, not a bug-fix. A collection of enum types are
changed to have start values with something other than 0. This avoids risk of
interpreting uninitialized value (0) as a valid enum value. There is no
functional changes with this commit.
---
Changed enum types:
- message_type
- page_type
- btree_async_state
- GET_RC (Set GET_RC_SUCCESS to 0 explicitly)
- memtable_state
- routing_async_state
- task_type
- trunk_subbundle_state
- lookup_type
- async_state
- async_lookup_state

(#395) Redefine start-value of various enum-types to be something other than 0. (0 usually means uninitialized value.)

---

src/btree.c
src/data_internal.h
src/trunk.c

In `btree_insert` and `btree_pack`, invalid user-type messages are not
handled properly. This change makes those functions return an error
when they receive invalid user-type messages. An error that
`btree_insert` returns is forwarded to an application. On the other
hand, when `btree_pack` returns an error, the program will be
asserted.

(#120) Handle invalid user-type messages in 'btree_insert' and 'btree_pack'

---

include/splinterdb/splinterdb.h
src/splinterdb.c
src/splinterdb_private.h
tests/unit/splinterdb_quick_test.c

This commit fixes a latent bug in splinterdb_iterator_init() which might
cause splinterdb_iterator_valid() to incorrectly return FALSE when
min_key is configured. Add a test case to demonstrate the problem,
albeit one that only fails in debug-mode.
As a defensive check against test/user-code attempting to add invalid
keys, add debug assertion checks in insert code-flow to validate that
keys are within the valid [min,max] key-range.
(This issue and the consequent bug-fix is rather temporary and may all
be dismantled once min/max key configuration is undone.)

(#419) Fix bug in splinterdb_iterator_init() when min_key is configured.

---

Makefile
docs/README.md
examples/README.md
examples/splinterdb_custom_ipv4_addr_sortcmp_example.c
examples/splinterdb_intro_example.c
examples/splinterdb_iterators_example.c
examples/splinterdb_wide_values_example.c
src/trunk.c
test.sh

This commit adds a small number of C-sample programs, to demonstrate use of SplinterDB core APIs.
Associated changes to build this set of stand-alone programs applied to `Makefile`. A small new "test-case" is added to
`test.sh` to always execute these programs as part of default testing set.
Associated docs files are also updated to direct the user to these programs.

Set of example C-programs, to demonstrate use of SplinterDB APIs.

---

ci/jobs.lib.yml
ci/pipeline.yml
ci/steps.lib.yml

msan CI jobs on pull-requests are timing out at 3 hours.
Two changes:
1. The sanitizer jobs (msan and asan) will now only run nightly, not on every pull-request
2. The timeouts on various jobs are longer, since recent test-runs have been hitting existing timeouts

CI updates: extend timeouts, sanitizer jobs only run nightly

---

.gitignore

on a fresh checkout, a `make` dirties the working directory.  this keep it clean.

git ignore build dir

---

ci/pipeline.yml

gcc doesn't support msan and its too confusing to mix them

ci: run sanitizers with clang

---

include/splinterdb/splinterdb.h
src/splinterdb.c

Header comments should explain to callers how long certain objects need to live.
- The user-provided `data_config` needs to live at least as long as the `splinterdb`
- The `splinterdb` needs to live at least as long as any `lookup_result` objects used with it

clarify lifetimes in code comments

---

examples/splinterdb_intro_example.c
examples/splinterdb_wide_values_example.c
include/splinterdb/splinterdb.h
src/splinterdb.c
tests/unit/splinterdb_quick_test.c

We don't need to pass the splinterdb instance in again on `splinterdb_lookup_result_value()`.
In the future, it could be stashed in the `lookup_result` when the `lookup_result` is first `init()`ed, and it could be checked at `lookup()` time.  But the `_value()` function is just an accessor.

simplify signature of lookup_result_value

---

include/splinterdb/splinterdb.h
src/splinterdb.c

The application-facing, opaque `splinterdb_lookup_result` and its internal representation `_splinterdb_lookup_result` should have the same alignment.

fix alignment of lookup_result

---

src/clockcache.c
src/clockcache.h
src/splinterdb.c
tests/functional/btree_test.c
tests/functional/cache_test.c
tests/functional/filter_test.c
tests/functional/log_test.c
tests/functional/splinter_test.c
tests/functional/ycsb_test.c
tests/unit/btree_stress_test.c
tests/unit/limitations_test.c
tests/unit/splinter_test.c

`clockcache_init` took a handle on the task system but clockcache never used it anywhere.  Removing it makes it easier to instantiate the cache.

eliminate vestigial task handle from cache

---

Makefile

Without this, a clean checkout followed by `make install` will error.

make install depends on libraries

---

include/splinterdb/limits.h
src/splinterdb.c

This change lets you set `MAX_KEY_SIZE` at build-time without editing the source code, e.g.
```sh
CFLAGS='-DMAX_KEY_SIZE=24' make
```
Also removes an old `#define MAX_KEY_STR_LEN 128` which has been unused since 11481016abf9779b397b4ff14eb3e744376c2040

Allow overriding MAX_KEY_SIZE via CFLAGS env var

---

tests/test_common.c

Thanks to @mdcallag finding the bug and suggesting this fix.
Fixes #440

Fix memory leak in verify_tuple

---

src/platform_linux/laio.c
src/platform_linux/platform.c
src/platform_linux/platform.h
src/rc_allocator.c
src/task.c
tests/unit/btree_stress_test.c
tests/unit/btree_test.c

This commit introduces a small renaming to a couple of memory-allocation caller-macros, and introduces couple of new ones. No functional changes are introduced.
- Rename: TYPED_MALLOC_MANUAL() -> TYPED_MANUAL_MALLOC(), TYPED_ZALLOC_MANUAL() -> TYPED_MANUAL_ZALLOC()
- Add: TYPED_ALIGNED_MALLOC(), TYPED_ALIGNED_ZALLOC()
- Replace raw call to platform memory allocation in one instance with use of TYPED_ALIGNED_ZALLOC().
- Add comments declaring parameters to various macros, and general improvement of comments related to these macros.

(#446) Rename couple of memory allocation macros. Add comments; code cleanup in platform.h

---

test.sh

The script test.sh has several inline calls to run different tests. Many of these are interesting cases to be run with an upcoming feature to run Splinter using allocated shared memory segments.
This commit rearranges and refactors inline calls to run diff tests into new functions that will now execute a collection of related tests.
Examples of new functions added are:
- run_fast_unit_tests(), run_slower_unit_tests()
- run_splinter_functionality_test(), run_splinter_perf_tests()
and so on. No changes are made to the set of tests that will be executed. This refactoring lays down the stage to re-execute relevant set(s) of tests using shared-memory.

(#444) Refactor chunks of test.sh into functions for code-reuse

---

Makefile
src/platform_linux/platform.c
src/platform_linux/platform.h
src/task.c
src/task.h
test.sh
tests/unit/task_system_test.c

This commit adds a bit of code cleanup to the task system module, task.c . No new functionality or change-in-logic is being done. Add new unit-test, task_system_test, to validate internal state of the task system for simple task creation / execution.
---
NOTE: to the reviewer. This change set came out of my code walk through to understand the task system and its innards.
This was done in context of the design rework to support execution of Splinter using allocated shared memory segments.
While at it, I constructed a small C-unit test to work through task system interfaces and to confirm, via tests, expected outputs.
Some of this testing will also be helpful when we "cut-over" to running tests using shared segments.

(#448) Clarify logic in task.c; Add unit-test to validate public interfaces.

---

include/splinterdb/splinterdb.h
src/splinterdb.c
src/trunk.c

Adds splinterdb_print_[insertion,lookup]_stats and splinterdb_reset stats to include/splinterdb/splinterdb.h.

Expose stats in splinterdb layer

---

src/rc_allocator.c

In a separate dev-effort, while running large inserts stress tests, I ran into a signal as reported in this issue.
It's a mystery why we are not seeing this signal in other performance benchmarking efforts.
Several efforts were made to develop `large_inserts_stress_tests` to reproduce this issue, but to no avail.
The missing virtual function pointer is a clear bug from code-inspection.
Hence, I am pushing this change to a PR for integration to /main.

Fix missing initialization of rc_allocator_in_use_virtual fn in rc_allocator_ops{} virtual functions table.

---

src/trunk.c

This commit fixes a missing free for memory allocated to the fingerprint array. The problem was seen to occur in highly concurrent inserts stress workload developed as part of concurrent POC-development and is difficult to reproduce in standalone Splinter.
In trunk_compact_bundle(), for a specific code-flow when we found no newly split siblings to replace with a new branch, we release the memory allocated for the trunk_compact_bundle_req{} struct, and exit processing. But the memory allocated (elsewhere, previously) for the fingerprint array hanging off this req struct remains unfreed.
This fix was identified through trace diagnostics and code walk through. And has been independently verified to fix this memory leak in the stress workloads that were used to generate this error.

(#481) Fix missing free for fingerprint array in trunk_compact_bundle()

---

src/btree.c
src/trunk.c

I'd be happy to extend this to also add a flag in trunk nodes to record when a node needs a split (due to a prior failure) so that a split will be forced next time we flush to it.
I _think_ the current splitting policy will already cause the node to split on the next flush, but it would be reasonable to add some mechanism to force that to happen no matter what the splitting policy is.

make compaction failures carry on

---

src/rc_allocator.c
src/splinterdb.c
src/trunk.c
tests/unit/task_system_test.c

Changes the default filter config so that the system doesn't print a warning.
Removes allocator, trunk, and task test printing.

Fix Default Filter Config and Remove Superfluous Printing

---

Makefile
README.md
ci/steps.lib.yml
test.sh

Adds a new target, run-example, which runs as part of CI but not part of any version of "run-tests".

tweak example running policy

---

include/splinterdb/platform_linux/public_platform.h
src/merge.c
src/platform_linux/platform.c
src/trunk.c
tests/functional/test_dispatcher.c
tests/functional/test_functionality.c

Fixes #441 , mostly.
Info messages now default to `/dev/null`.  Error messages still go to stderr.
The app may customize that by calling a new function `splinterdb_logs_set_streams()`.
A future PR could provide command-line or env-var control over _test_ output.

Enable application to silence info logs

---

src/splinterdb.c

This was being automatically corrected in the trunk config init and triggering junk messages.

Set default filter index size to 512

---

src/trunk.c
src/trunk.h

Refactors handling of trunk nodes to a new trunk_node struct, rather than using page_handles. This is now analagous to the handing of btree_nodes.
Moves the related low-level trunk node functionality to a new header src/trunk_node.h. This header will eventually hold all low-level trunk node functionality.
Moves the trunk node logging functionality to a new header src/trunk_log.h.
Moves the superblock functionality to a new header src/superblock.c. This should simplify the eventual change to calling these functions from src/splinterdb.c.
Fixes a use-after-free bug where `trunk_node_verify` is called on the child in a debug_assert after a trunk_split_leaf, which ungets the child.

Refactor Trunk Node Handles

---

src/platform_linux/laio.c
tests/unit/splinterdb_quick_test.c

When file open fails, return error code instead of crashing

---

include/splinterdb/data.h
include/splinterdb/platform_linux/public_platform.h
include/splinterdb/public_platform.h
include/splinterdb/public_util.h
src/allocator.h
src/btree.h
src/btree_private.h
src/cache.h
src/clockcache.h
src/data_internal.h
src/io.h
src/iterator.h
src/log.h
src/memtable.h
src/merge.h
src/mini_allocator.h
src/pcq.h
src/platform_linux/laio.h
src/rc_allocator.h
src/routing_filter.h
src/shard_log.h
src/srq.h
src/task.h
src/trunk.h
tests/config.h
tests/functional/test.h
tests/functional/test_async.h
tests/test_common.h
tests/test_data.h
tests/unit/btree_test_common.h

Switch from matched-ifndef blocks to the "nonstandard but widely supported" #pragma once. This has the nice benefit that there's no possibility of name collision, no need to rename the ifndef if you rename a file later, and just generally less boilerplate clutter to sift through.

use pragma once in preference to matched ifndef blocks

---

include/splinterdb/splinterdb.h
src/splinterdb.c
src/task.c
src/task.h
test.sh
tests/config.c
tests/config.h
tests/functional/btree_test.c
tests/functional/cache_test.c
tests/functional/filter_test.c
tests/functional/log_test.c
tests/functional/splinter_test.c
tests/functional/test.h
tests/functional/ycsb_test.c
tests/unit/btree_stress_test.c
tests/unit/config_parse_test.c
tests/unit/limitations_test.c
tests/unit/splinter_test.c
tests/unit/splinterdb_quick_test.c
tests/unit/task_system_test.c

This commit exercises use of background threads, a feature that has been implemented but hadn't been fully tested & engaged.
- Minor adjustments are done to task system initialization to manage the order in which background threads are started up.
- Fixed some checks in task_system_test to cope with the new variation that this test case could, optionally, be exercised with `--num-normal-bg-threads` | `--num-memtable-bg-threads` arguments.
- Enhanced config_parse() to recognize these two new options.
- Added a case to test.sh to exercise the task_system_test with background threads.
-  Stabilization fixes to get large inserts stress tests working. (New test withdrawn)
-  Add new test cases to test.sh, exercising background threads.
---------------
**NOTE**: Before you can run the …

Enable use of background threads in Splinter. Engage tests to verify basic stability of this existing feature.

---

src/clockcache.c
src/io.h
src/platform_linux/laio.c
src/platform_linux/laio.h
src/rc_allocator.c
src/splinterdb.c
test.sh
tests/functional/io_apis_test.c
tests/functional/test.h
tests/functional/test_dispatcher.c

This commit adds a new `io_apis_test` target under `functional/driver_test`.
This new test exercises sync IO APIs and async reads APIs, as a way to do minimal validation of the IO sub-system and its APIs. 
Minor code & comment cleanup is done in `laio.c` to improve readability and understanding of this module. 
Few existing error & assertion messages reporting IO errors are enhanced to report more diagnostic data that lead to said errors. Most of these are around I/O calls and seen while opening a SplinterDB device.
**No new functional changes** are introduced with this commit.
Most of the changes in `laio.c` add clarifying comments / fn-prologs to improve overall readability. 
Some existing asserts are expanded to print additional diagnostic data to improve troubleshooting of IO errors …

(#456) Add io_apis_test IO exerciser. Minor cleanup of laio.c

---

src/allocator.h
src/btree.c
src/cache.h
src/clockcache.c
src/io.h
src/memtable.c
src/mini_allocator.c
src/rc_allocator.c
src/rc_allocator.h
src/routing_filter.c
src/shard_log.c
src/splinterdb.c
src/trunk.c
tests/functional/btree_test.c
tests/functional/cache_test.c
tests/functional/filter_test.c
tests/functional/log_test.c
tests/functional/splinter_test.c
tests/functional/test.h
tests/functional/test_functionality.c
tests/functional/ycsb_test.c
tests/unit/btree_stress_test.c
tests/unit/btree_test.c
tests/unit/btree_test_common.c
tests/unit/btree_test_common.h
tests/unit/config_parse_test.c
tests/unit/limitations_test.c
tests/unit/splinter_test.c

This change reduces the width of the polymorphic cache interface by moving things that only depend on the allocator to the allocator.

Jonh move extent funcs to allocator

---

src/btree.c

This commit adds following stand-alone fns to print diff BTree sub-structs:
- btree_print_btree_pivot_stats()
- btree_print_btree_pivot_data()
- btree_print_index_entry()
- btree_print_leaf_entry()
Existing print code inline in other methods is pulled-out into above functions to facilitate code-reuse and the ability to call from the debugger. No changes are done to existing functionality of print methods.
----
NOTE: This modularization sets up the stage to enhance the printing of BTree pivot stats in `btree_print_btree_pivot_stats()` to also print the `bytes` value as a string with unit-specifiers. This is an in-flight concurrent change under PR #512, also under review at this time. 
I'd like to integrate this change-set first and then lay down the above change-set.

(#520) Refactor few BTree print code chunks into sub-functions.

---

src/splinterdb.c
src/trunk.c
src/trunk.h
tests/functional/test.h
tests/unit/limitations_test.c

This commit does a minor cleanup in `trunk_config_init()` to correctly report the value for 'Maximum key size' reported when the checks fail for an invalid configuration. We were overflowing the value for an uint64 variable, leading to bogus values reported in the error. Changed this function and other helper functions in test-code that parse command-line arguments to return platform_status. Adjust the handling of this failed return-value in diff test code. Add new unit-test to verify that invalid config params correctly fail to init the trunk-config.
--- NOTE: While at it, I changed the code in `trunk_config_init()` from a `platform_assert()` to a clean error message. 
This should improve the usability of the library when, say, invoking `driver_test` with bogus configs that fail to init …

(#342) Fix checks in trunk_config_init() to report correct arg-values.

---

src/allocator.h
src/clockcache.c
src/mini_allocator.c
src/shard_log.c
src/trunk.c

The function returns a count of references, not a reference.
Fixes #517.

Rename allocator_get_ref to _get_refcount

---

Makefile

This commit replaces all uses of shell 'find', 'grep' commands in Makefile with built-ins such as 'wildcard', 'filter-out' etc. This removes any potential dependency on shell commands for 'make' invocations. A small change is to list the unit-test sources in lex-sorted order when linking them into the unit_test binary.

(#290) Replace use of 'find', 'grep' with Makefile built-in 'wildcard' command.

---

src/clockcache.c
test.sh

This commit fixes off-by-1 issues checking MAX_THREADS value in assertions in `clockcache.c` . These problems are easily reproduced with `driver_test splinter_test ` with max # of threads. A new test execution with --num-insert-threads 63 is added to nightly runs, in test.sh .
----
The issue #509 fully describes the repro and assertions seen.
These problems were discovered during an in-flight integration while exercising `MAX_THREADS` threads. These fixes were applied to the dev-branch and allowed testing to continue.
Integrating these to /main will help improve overall stability.

(#509) Fix off-by-1 issues re. MAX_THREADS in clockcache.c

---

Makefile
src/clockcache.c
src/clockcache.h
src/platform_linux/platform.c
src/platform_linux/platform.h
src/rc_allocator.c
src/rc_allocator.h
src/splinterdb.c
tests/functional/btree_test.c
tests/functional/cache_test.c
tests/functional/filter_test.c
tests/functional/log_test.c
tests/functional/splinter_test.c
tests/functional/test_functionality.c
tests/functional/test_functionality.h
tests/functional/test_splinter_shadow.c
tests/functional/test_splinter_shadow.h
tests/functional/ycsb_test.c
tests/unit/btree_stress_test.c
tests/unit/platform_apis_test.c
tests/unit/splinter_test.c

This commit reworks the interfaces of `platform_buffer_create()` and `platform_buffer_destroy()` to now become `platform_buffer_init()` and `platform_buffer_deinit()` interfaces.
This removes a dependency on `platform_heap_id` or `platform_heap_handle` arg. 
This change does not functionally change anything in these methods. Also, this (indirectly) fixes a minor bug in the create function to deal with the (very rare) case of failing to allocate memory from the heap for `buffer_handle *bh` . Added small unit-test, platform_apis_test, to exercise these changes.
---
NOTE: This is some common infra-code built in a prototype dev branch for supporting different memory handles.
I'm pulling this piece out on its own for integration to /main, so that this ground work can be laid for integrating …

(#507) Change platform_buffer_create()/destroy() interfaces to platform_buffer_init() / deinit() methods.

---

src/task.c
tests/unit/task_system_test.c

This commit applies some minor clean-up to task system as a follow-on to the larger rework done under PR #497. Consistently use STATUS_BUSY, as a way to report when all concurrent threads are in-use. This will result in a `Resource temporarily unavailable` message to the client. Minor changes to task system unit-test code & cleanup of comments.
--- NOTE to the reviewer:
Nothing is changing substantially; minor corrections to keep code & test code consistent.

(#499) Minor cleanup of INVALID_TID, and MAX_THREADS in task-system

---

src/btree.c
src/platform_linux/platform.h
src/rc_allocator.c
src/rc_allocator.h
src/trunk.c
src/util.c
src/util.h
tests/unit/btree_stress_test.c
tests/unit/misc_test.c

This commit adds couple of utility functions to convert 'size' unit to a human-readable string with unit-specifiers, in an output buffer.
- size_to_str() - Convert 'size' to a string in an output buffer
- size_to_fmtstr() - Same as above, using user-specified format-string. Useful to generate output enclosed in '(%s)'.
Add utility bytes to Units conversion macros. Add test cases to exercise these interfaces. Apply these utility fns in couple of stats-printing methods, to display values in units of bytes as a string.
---
NOTE: This work was done in an in-flight integration development branch, to closely track memory usage (free / allocation metrics). The utility methods have been formalized, productized with new unit-tests. 
This commit applies the conversion functions to couple of …

(#511) Add fns to print 'size' as human-readable string w/ unit-specifiers.

---

Makefile
tests/unit/btree_stress_test.c
tests/unit/limitations_test.c
tests/unit/misc_test.c
tests/unit/platform_apis_test.c
tests/unit/splinter_test.c
tests/unit/splinterdb_quick_test.c
tests/unit/splinterdb_stress_test.c
tests/unit/task_system_test.c
tests/unit/unit_tests.h
tests/unit/unit_tests_common.c

This commit refactors existing chunks of code that exists in different unit- test sources to manage output file handles to a common function, now defined in new file `unit/unit_tests_common.c` ; `set_log_streams_for_tests()`.
Tests that check error-raising behaviour will now need to call `set_log_streams_for_neg_tests()`, to manage output streams.
Minor correction to `TEST_DB_NAME`; change it to conform to the r.e. defined in .gitignore to suppress listing this in 'git status' output.
----
NOTE: I did not try to make this even more generic beyond unit-tests to have `functional/ tests` also call into these interfaces. That's why this new file `unit_tests_common.c` is in `tests/unit` sub-dir and not in top-level `tests/` dir.
I think, let's see how this settles down and if we ever find the …

(#513) Refactor into set_log_streams_for_tests() to manage unit-test outputs.

---

src/btree.c

This commit fixes up several comments in btree.c to conform to the style we have followed elsewhere for multi-line comments. No code changes are done with this change.

Fix-up indentation of multi-line comments to conform to coding standards

---

tests/unit/large_inserts_bugs_stress_test.c
tests/unit/splinter_shmem_test.c
tests/unit/splinter_test.c
tests/unit/splinterdb_forked_child_test.c

Also, minor fix in exec_worker_thread() in large_inserts_bugs_stress_test.c to avoid divide-by-0 error when elapsed_ns is too small.
-- Note to @rosenhouse : With this change, all unit-tests added newly by my shared-memory prototype work are changed to consistently use `CTEST_LOG_INFO()`. This brings them in-sync with recently added unit-test verbosity levels interfaces and behaviour.
Here is the confirmation:
```
agurajada/gabe/shmem-squash-logging-ovhds-poc
sdb-fdb-build:[16] $ grep -l -w platform_log *.c
sdb-fdb-build:[17] $ grep -l -w platform_default_log *.c
```

Replace all instances of platform_default_log() with CTEST_LOG_INFO()

---

include/splinterdb/splinterdb.h
src/cache.h
src/clockcache.c
src/log.h
src/platform_linux/laio.c
src/platform_linux/platform.h
src/platform_linux/shmem.c
src/shard_log.c
src/shard_log.h
src/splinterdb.c
src/trunk.c
tests/config.c
tests/config.h
tests/functional/log_test.c
tests/functional/test.h
tests/unit/large_inserts_bugs_stress_test.c
tests/unit/main.c

This is a collection of multiple commits that bring-in support for `COMMIT` capability in the SplinterDB library.
This is stitched through in `large_inserts_bugs_stress_test.c`, with new `--commit-every` option. Test is enhanced to now run with `--log` option, which will turn logging ON.

Add COMMIT support; add splinterdb_commit(). --commit-every test option. Update unit tests.

---

src/task.c
src/task.h

This commit removes the dependency of task system structures on global variables declared in `task.c` . The hook-related variables are now moved as members of the `task_system{}` struct. This removes accessing potentially stale values when task-system is destroyed and re-created. Also, `TASK_MAX_HOOKS` is now decreased from 8 to 4. This change largely has no functional impact, and is mostly a test-stabilization fix.
---
NOTE: The issue #500 describes in fuller detail why these global variables could present a problem in a testing scenario, e.g., when we do re-create a task-system by performing `task_system_destroy()` followed by `task_system_create()`.

(#500) Move hook-related global vars to task_system{} struct.

---

src/btree.c
src/btree.h
src/data_internal.h
src/memtable.h
src/trunk.c
tests/functional/btree_test.c
tests/unit/btree_stress_test.c
tests/unit/btree_test.c

This commit extends BTree-printing routines to also report the page type, whether it's a branch or a memtable BTree. As the structures and print methods are shared between two types of objects, this extra information will help in diagnostics.

Identify Memtable v/s Branch page types via BTree-print routines.

---

ci/jobs.lib.yml
ci/pipeline.yml
ci/resources.lib.yml
ci/sequences.lib.yml
ci/steps.lib.yml
ci/tasks/pr-check-shell-scripts.sh

CI currently tests
- every commit to `main`
- every pull-request that targets `main`
- every night it runs some slower tests against the latest commit on `main`
But we may want to have more than 1 long-lived branch that receives this kind of test coverage.
This PR refactors the configuration for CI to us to enable that.

CI can cover multiple trunk branches

---

ci/pipeline.yml
ci/sequences.lib.yml

1. The branch `shmem` is now covered by CI.  Commits to it, and PRs to it will get CI tests run and reported.  Additionally, the `nightly` job will also run against this branch as well as `main`. 
2. MSAN and ASAN jobs will now run on all pushes to all PRs to `main` and `shmem`.  They run in parallel to the other jobs, and based on recent run-times, shouldn’t even be the longest job to complete (that’s currently the `debug-gcc` one).  They are currently non-blocking on PRs (though that can be toggled via the GitHub repo settings).
Item 1 is a 1-line change to the `branches` variable in `pipeline.yml` and is easily reverted once the `shmem` branch merges.  Item 2 can stick around.

CI follow-up

---

test.sh
tests/functional/filter_test.c
tests/functional/io_apis_test.c

This commit fixes minor errors in 2 tests (io_apis_test, filter_test) to get them running cleanly in ASAN-builds.

(#554) Fixes to get couple of tests running cleanly in ASAN-builds

---

ci/pipeline.yml

This change has already been applied to CI, so we can see the results of it live.

CI: use gcc for ASAN jobs

---

src/btree.c
src/clockcache.c
src/routing_filter.c
tests/unit/splinterdb_stress_test.c

This commit fixes a simple arithmetic error in `routing_filter_prefetch()` while computing next page's address. A new test case `test_issue_458_mini_destroy_unused_debug_assert` has been added to existing `unit/splinterdb_stress_test`, which reproduces the problem.
NOTE: Even with this fix, this simple test case does not succeed in debug builds. We are failing with a new assertion:
```
(gdb) c
Continuing.
btree_pack(): req->num_tuples=6291456 exceeded output size limit, req->max_tuples=6291456
btree_pack(): req->num_tuples=6291456 exceeded output size limit, req->max_tuples=6291456
[Switching to Thread 0x7ffff6894640 (LWP 484069)]
Thread 4 "splinterdb_stre" hit Breakpoint 1, trunk_flush_into_bundle (spl=0x7fffb5f8c040, parent=0x7ffff68917c0, child=0x7ffff6891620, pdata=0x7fffd355458c, …
```

(#561) Fix routing_filter_prefetch() to account for page-size while computing next page-address.

---

include/splinterdb/data.h
include/splinterdb/platform_linux/public_platform.h
include/splinterdb/public_util.h
include/splinterdb/splinterdb.h
src/btree.c
src/data_internal.c
src/platform_linux/platform.h
src/routing_filter.c
src/routing_filter.h
src/splinterdb.c
tests/functional/splinter_test.c
tests/functional/ycsb_test.c

In SplinterDB's public splinterdb_config{} config, we have few fields defined as 'bool' which is typedef'ed to int32 on our side. This creates compatibility problems when linking this library with other s/w which may have defined 'bool' as 1-byte field. (Offsets of fields in the splinterdb_config{} struct following 1st field defined as 'bool' changes across objects. This commit addresses this issue by defining boolean fields in public struct to be of type `_Bool`. This should, hopefully,reduce the risk of such incompatibilities. 
(Splinter's internal definition of `bool` remains as `int32`, to avoid any other product change / compatibility issues.)
Found only one instance where 'bool' return value from routing_filter_is_value_found() had to be adjusted to fit 1-byte return value.

(#548) Change typedef of bool from int32 to 1-byte 'unsigned char'.

---

include/splinterdb/data.h
include/splinterdb/platform_linux/public_platform.h
include/splinterdb/public_util.h
include/splinterdb/splinterdb.h
src/btree.c
src/data_internal.c
src/platform_linux/platform.h
src/routing_filter.c
src/routing_filter.h
src/splinterdb.c
src/util.c
tests/functional/splinter_test.c
tests/functional/ycsb_test.c
tests/unit/misc_test.c

Fractional portion of value formatted by size_to_str() was incorrect. We were losing the scale for things which were supposed to be "xx.07", we were reporting "xx.7", which is incorrect.

Fix bug in output formatted by size_to_str() helper.

---

ci/steps.lib.yml

In-flight stabilization of shared memory support in Splinter is bringin along with tons more additional tests. We are effetively running most of the existing twice; once w/o and once w/ shared memory configured. Debug-build test runs are timing out at 2 hours. Bump timeout to 3hs, and once stabilized, we can look into dropping this to 2h.

CI: Bump timeout from 2h to 3h. shmem-tests cause debug test runs to take longer.

---

src/allocator.h
src/clockcache.c
src/data_internal.c
src/memtable.c
src/memtable.h
src/platform_linux/platform.c
src/platform_linux/platform_types.h
src/trunk.c
src/trunk.h
tests/config.c
tests/functional/btree_test.c
tests/functional/splinter_test.c

This changeset implements copy-on-write for trunk nodes, which includes several high-level changes. This PR still needs to be rebased onto main, but the the purpose is to discuss high- and low-level design decisions.
Changes in this PR:
1. Trunk root lock. A distributed RW lock is used to access/change the current root.
2. Flush from root. Flushes proceed from the root and cascade immediately rather than being triggered at the beginning of `trunk_compact_bundle`.
3. Copy-on-write. Trunk nodes cannot be modified directly, and instead are change via a copy-on-write of the root-to-node path together with a change of the root node.
4. Garbage Collection for unlinked branches and filters. After a copy-on-write, the nodes on the old path will be unreferenced. This PR does not GC the trunk nodes …

Copy-on-write Trunk

---

src/trunk.c

Previously, when `trunk_stats_reset()` was called by splinterdb_stats_reset(), the entire statistics of a trunk, including the histogram handles, were reset to zero.

(#546) Fix the segmentation fault after splinterdb_stats_reset()

---

src/trunk.c
src/trunk.h

This pull request does:
1. Fixes an assertion bug in `trunk_replace_routing_filter`. Previously we asserted that if we compacted down to an empty bundle then the filter must also be NULL. However, this is not necessarily the case. Changed the assertion to assert that if the compacted bundle and the filter are empty then the filter is NULL.
2. Simplifies the `trunk_range_iterator` struct by the removal of `local_max_key`. local_max_key is now a temporary variable in `trunk_range_iterator_init`.

Trunk Assertion Fix and Simplification

---

ci/pipeline.yml

I've applied this configuration already.  It appears to work.

CI fix: use new version of registry-image resource

---

src/trunk.c

`trunk_set_super_block()` is used when both creating and closing the splinterdb. However, `spl->log` is already freed and becomes NULL when it gets to this function. This causes a segmentation fault because `spl->log` is referenced when it stores the log addresses into the super block.  As a fix, it sets `super->log_addr` and `super->log_meta_addr` if `spl->log` is valid. Otherwise, they are set to 0.

(#581) Resolve a segmentation fault on trunk_unmount()

---

include/splinterdb/splinterdb.h
src/btree.c
src/btree.h
src/btree_private.h
src/iterator.h
src/merge.c
src/merge.h
src/routing_filter.c
src/shard_log.c
src/splinterdb.c
src/trunk.c
src/trunk.h
tests/functional/btree_test.c
tests/functional/log_test.c
tests/functional/test_functionality.c
tests/unit/btree_stress_test.c
tests/unit/btree_test.c
tests/unit/splinterdb_quick_test.c
tests/unit/splinterdb_stress_test.c

This PR allows splinter iterators to be bidirectional. To do this
- It renames some of the iterator functions to make them more direction-neutral.  For example, "advance" is renamed "next", so that we can add a "prev".  "at_end" becomes 3 functions "can_prev", "can_next", and "can_curr" which allow for more granular bounds checking and inform us of what state the iterator is in.
- It changes the possible states of an iterator to: 
- `before start`: Allowed to call "next", not allowed to call "get_current" or "prev"
- `in range`: Allowed to call all operations
- `after end`: Allowed to call "prev", not allowed to call "get_current" or "next"
- `empty`: Not allowed to perform any operations.
- It changes which iterator operations can fail:  Now, only the "next" or "prev" method can fail. …

Bidirectional Iterators

---

src/platform_linux/platform_inline.h

This PR fixes #595 about a compile error when using `platform_open_log_file()` and a wrong parameter name for `platform_close_log_file()`.

Fix the compile error on platform_open_log_file()

---

Makefile
test.sh
tests/unit/large_inserts_stress_test.c

Upcoming PR #569 is overhauling large-inserts stress test. To simplify examining the diffs of this test case as part of that review, this commit is renaming the test file to large_inserts_stress_test.c, with appropriate changes to the build-and-test files.
No new tests / changes are added as part of this commit.

Rename large_inserts_bugs_stress_test.c -> large_inserts_stress_test.c

---

test.sh

This commit adds minor improvements / bug-fixes to test.sh:
- The capability to run individual test-function(s) by name was only working with the "--use-shmem" flag but was not working when `test.sh` is invoked with just the `test-execution-fn-name`. We would get a bash parameter parsing error.
Rework the parameter parsing in all test-functions so that we can now invoke this driver script as:
$ INCLUDE_SLOW_TESTS=true ./test.sh run_slower_unit_tests
This will run individually named test-functions with default memory configuration.
- run_other_driver_tests() had a bug where tests run by this function were not honoring '--use-shmem' arg. Fix this so that cache_test, log_test, filter_test can now also be run with "--use-shmem" enabled.
- Update elapsed-time tracking to separately track the …

test.sh: Enable running by named-function w/o shared memory.

---

src/btree_private.h
src/clockcache.c
src/mini_allocator.c
src/routing_filter.c
src/trunk.c
tests/unit/btree_stress_test.c
tests/unit/btree_test.c

In debug-build test runs, profiling shows interfaces like clockcache_page_size(), clockcache_config_page_size() bubbling up to top of 'perf top' output. This commit attempts to reduce multiple calls to lookup functions to retrieve the page-size, by caching the page-size once per function where it's used multiple times.
The affected interfaces are: btree_page_size(), clockcache_page_size(), cache_page_size(), cache_config_page_size(), trunk_page_size() and few similar ones.
These changes add up to saving few seconds of test-execution (out of few mins of run-time) in debug-build mode, esp for BTree-related tests.
---
```
cc-sdb-vm:[7] $ tail -100 /home/agurajada/tmp/test.nightly.dbg.main.out | grep BTree
BTree test, key size=8 bytes                                                         : …
```

(#604) Cache page-size in local variables to reduce multiple lookups.

---

src/platform_linux/shmem.c

Upcoming PR #569 is bringing-in support for handling small fragments. This commit renames existing variables, field names and a few function names that deal with large-fragment support to consistently use 'large' in the name. This clears the way in the namespace for upcoming small-fragment changes.
Some examples:
- struct shm_frag_info -> struct shm_large_frag_info
- E.g., shm_frag_addr -> frag_addr, shm_frag_size -> frag_size ...
- shm_frag_info shm_mem_frags[] -> shm_large_frag_info shm_large_frags[]
- shm_num_frags_tracked -> shm_nlarge_frags_tracked
- platform_shm_find_free() -> platform_shm_find_large()
... **No other code-/logic-changes are done with this commit**.

shmem.c: Rename variables relating to large-fragment handling.

---

src/platform_linux/shmem.c

This commit refactors shared memory usage stats fields to drive-off shminfo_usage_stats{} struct entirely. Add platform_save_usage_stats(), used by platform_shm_print_usage().
This refactoring paves the way for upcoming PR #569 which is adding more memory-usage stats fields.
-----
There is zero logic change here. It's mainly a data structural change, rearranging where the memory-usage stats fields are tracked. They now belong to a common struct, so most of the diffs are to access the new `usage.<field>` reference.
Minor enhancements in the memory usage stats tracking / printing code is done, for improved understanding of memory usage metrics.

Refactor to save / print shmem usage stats using common struct.

---

src/platform_linux/laio.c
src/platform_linux/platform.c
src/platform_linux/platform_inline.h
src/platform_linux/shmem.c
src/routing_filter.c
tests/functional/io_apis_test.c
tests/test_common.c
tests/unit/btree_stress_test.c
tests/unit/large_inserts_stress_test.c
tests/unit/main.c
tests/unit/splinterdb_forked_child_test.c

This commit cleans-up the `#include <unistd.h>` from several .c files that needed access to get pid(). Instead, change the code to invoke platform_getpid(), now defined in platform_inline.h

(#599) Replace calls to getpid() with  platform_getpid()

---

src/btree.c

Leaf splits and iterator initialization both violate the dominators-based locking protocol.  Leaf splits need to get a write-lock on the leaf's successor node, but the splitting thread may not hold a lock on the dominating node of the leaf and its successor.  iterator initializers do two root-to-leaf traversals, the second while holding a claim on the leaf found in the first.  So again they may hold locks on two nodes without holding a lock on their common dominator.
As a result, they can deadlock.  The specific deadlock I saw was that the splitting thread held a write lock on the leaf's parent, which happened to also be the root of the tree.  It also held a claim on the leaf and was looping trying to claim the leaf's successor.  The iterator initialization thread had already done its …

Fix btree deadlock between leaf splits and iterator initialization.

---

src/task.c
tests/unit/task_system_test.c

If `MAX_THREADS` is not a multiple of 64, the assertion in `task_system_destroy()` will fail.
https://github.com/vmware/splinterdb/blob/38258e197dd05c057ff8bbf70dbfa09ed515b5f0/src/task.c#L952
Previously, tid_bitmask was initialized with only the bit corresponding to the thread ID set to 1, while the rest were 0. Now, all 64 bits are initialized to 1.

Set all 64 bits of tid_bitmask[i] to 1
